### ISSUE TITLE
Cannot work with Forge on 1.12.2 version.

### ISSUE THREAD

**Issue by ryan-si** [MinecraftMachina/multimc-macos-arm64#31]
It's said that I need a Java of 64bit version.
But I certainly installed the zulu Java 64bit version for the Arm at this link.
https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk

<img width="512" alt="image" src="https://user-images.githubusercontent.com/43299793/154693434-b0953884-5e21-4fbb-b094-5dbcfc2fa84a.png">

**Comment by ryan-si** [comment]
Checking Java version...
Java is version 17.0.2, using 32-bit architecture, from Azul Systems, Inc..


Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

**Comment by ViRb3** [comment]
> Checking Java version...
Java is version 17.0.2, using 32-bit architecture, from Azul Systems, Inc..

You need Java 8 to play on Forge 1.12.2. Check the [troubleshooting](https://github.com/MinecraftMachina/ManyMC#troubleshooting) sections in the README, it will have all you need.
 
> Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

ManyMC was unable to detect the architecture properly (#20), so that error was misleading. Please get the [latest version](https://github.com/MinecraftMachina/ManyMC/releases/tag/v0.0.6) of ManyMC, which has this problem fixed. You definitely want arm64/aarch64, though.
