### ISSUE TITLE
Add Quilt Launcher Support

### ISSUE THREAD

**Issue by rinOfTheStars** [MinecraftMachina/multimc-macos-arm64#55]
See https://github.com/PolyMC/PolyMC/issues/406 and various related pull requests, mainly https://github.com/PolyMC/PolyMC/pull/185

**Comment by ViRb3** [comment]
Thanks for the suggestion. Unfortunately, this will not be possible due to license incompatibility between PolyMC and ManyMC. If MultiMC gets the feature, then I can pull it here.

**Comment by ViRb3** [comment]
Well, good news, seems like Quilt support was merged in MultiMC an hour ago. Will pull here soon.

**Comment by MattElek** [comment]
I know you've talked about wanting to follow MultiMC before on other issues and on discord, but PolyMC is really starting to have some compelling features. Is it possible for me to build against it?

**Comment by TAKfsg** [comment]
I agree, manymc should merge with polymc if that is possible.

**Comment by MattElek** [comment]
I’m not even proposing a merge, it’s ViRb’s project and he’s put in the work, it’s his to do with as he pleases. Last I heard he didn’t want to go down that route yet, but he also didn’t say it was completely out of the question. Just curious about where he stands on it and if a build against PolyMC is possible with minor effort.

**Comment by ViRb3** [comment]
Released in Build 9, so closing.

@MattElek It is not possible to pull any changes from PolyMC into ManyMC/MultiMC at all due to copyright license differences. It is only possible to merge ManyMC into PolyMC, and if that happens, there is no going back due to those same license differences. Because of these reasons, I am refraining from doing such a merge just yet. I want to track how PolyMC develops a bit more in the future, gain some more features, and then I can decide.

**Comment by d-513** [comment]
Just to clarify, it’s possible to take changes from PolyMC, but you would have to relicense ManyMC under GPL3 which could be problematic if multimc changes to ms-pl
