### ISSUE TITLE
Launch 1.19 with Microsoft Account - Could not create profile

### ISSUE THREAD

**Issue by kaihendry** [MinecraftMachina/multimc-macos-arm64#74]
<img width="727" alt="Screenshot 2022-07-22 at 8 01 56 PM" src="https://user-images.githubusercontent.com/765871/180435231-4a8cf832-0d3f-433e-a41e-c2ae18efae40.png">

It's prompts for a username. I enter a few variations, none work. All *Could not create profile*.

Do I need a Mojang account? Sorry I usually play Bedrock.

I'm using this launcher since I heard it works with M1.

**Comment by ViRb3** [comment]
If you only have Minecraft Bedrock Edition, you can't play Java Edition — they are separate games. You need to buy it separately. To be sure, use the official Minecraft launcher [here](https://www.minecraft.net/en-us/download) and see if it lets you play. If no, then you got your answer. Otherwise, this is a bug and I can investigate further.

**Comment by kaihendry** [comment]
I now appear to have the Java version. Can't seem to get cross-play working though.
![image](https://user-images.githubusercontent.com/765871/185772758-064af5cc-7a3c-4814-b5a9-588983055f2b.png)

**Comment by ViRb3** [comment]
What do you mean by cross-play? Java Edition and Bedrock Edition are very fundamentally different games and they do not have any native cross-play between them. There is [Geyser](https://github.com/GeyserMC/Geyser/) which is a third-party "bridge" that mostly lets you do that, but it has issues with anti-cheats.
