### ISSUE TITLE
PolyMC lead devs have gone rogue!

### ISSUE THREAD

**Issue by rinOfTheStars** [MinecraftMachina/multimc-macos-arm64#87]
I'm sure you've already seen this, but some of the old lead devs of PolyMC went rogue—causing the main meta-server to essentially send users malware (see https://github.com/PolyMC/PolyMC/commit/ccf282593dcdbe189c99b81b8bc90cb203aed3ee , warning for NSFW content and slurs being posted, because we can't have nice things on the internet) 

The actually active devs have forked the pre-trashing commit version of the PolyMC development branch to https://github.com/PlaceholderMC/PlaceholderMC, so I suppose that's where things are going to continue? I suggest that ManyMC doesn't update any metaserver stuff with upstream commits for the time being, obviously.

**Comment by nullTheCoder** [comment]
ManyMC seems to not be maintained anymore so as soon as I heard the news I immediately went back to manyMC.

**Comment by ViRb3** [comment]
Yes, I noticed the takeover as soon as this happened since I was kicked out of the PolyMC organization on GitHub.

Let's be accurate, there is no sign of malware at the moment — the meta has not been touched. With that said, the takeover is an act of stupidity and you should not trust such people with anything. I advise everyone to stop using PolyMC immediately.

ManyMC is unaffected by these actions as I have sole and full control over it. I have taken all safety measures and cut any ties between ManyMC and PolyMC. I also reverted ManyMC's meta to two weeks ago to ensure nothing sneaky was pulled in.

**Comment by NineEighty** [comment]
Is anyone else having issues connecting obtaining Curseforge Packs via ManyMC since this happened?

**Comment by ViRb3** [comment]
Yes, the CurseForge key used by ManyMC belonged to PolyMC, and it has been revoked.

**Comment by NineEighty** [comment]
> Yes, the CurseForge key used by ManyMC belonged to PolyMC, and it has been revoked.

Makes sense, whilst an inconvenience, it's good from a security perspective.

**Comment by mkaito** [comment]
Sounds like most of the people involved in Poly have moved shop to PrismLauncher: https://github.com/PrismLauncher/PrismLauncher

**Comment by tobimori** [comment]
PrismLauncher just released its first release with changes provided by ManyMC. Works perfectly on M1.

**Comment by ViRb3** [comment]
Yes, Prism is the continuation of PolyMC from the original maintainers. It is also the official continuation of ManyMC. More about this in the README and Discord.
